@startuml
hide empty methods
hide circle
skinparam roundcorner 5
skinparam linetype ortho
skinparam shadowing false
skinparam handwritten false
skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
    BorderColor<<contrib.auth>> green
}

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define primary_foreign_key(x) <b><color:#b8861b><&key></color><color:#aaaaaa><&key></color> x</b>
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>
!define tableAuth(x) entity x <<Outsystems>>

tableAuth( User ) {
  primary_key( Id ): INTEGER
  column( Name ): VARCHAR
  column( Username ): VARCHAR
  column( Password ): VARCHAR
  column( Email ): VARCHAR
  column( MobilePhone ): VARCHAR
  column( External_Id ): VARCHAR
  column( Creation_Date ): TIMESTAMP
  column( Is_Active ): BOOLEAN
}

table( OnBoardingUser ) {
  primary_foreign_key( UserId ): INTEGER <<FK>>
  column( IdentificationNumber ): INTEGER
  column( PhoneNumber ): INTEGER
  column( Email ): VARCHAR
  column( HasSBVKnowledge ): BOOLEAN
  column( HasAgreedWithTerms ): BOOLEAN
  column( Signature ): BINARY DATA
}

table( Profile ) {
  primary_key( IdentificationNumber ): INTEGER
  foreign_key( UserId ): INTEGER <<FK>>
  column( Name ): VARCHAR
  column( Surname ): VARCHAR
  column( Address ): VARCHAR
  column( DateOfBirth ): TIMESTAMP
  column( Gender ): VARCHAR
  column( EmergencyContact ): VARCHAR
  column( BloodType ): VARCHAR
  column( HasCronicalDisease ): BOOLEAN
  column( CronicalDiseases ): VARCHAR
  column( HasAllergies ): BOOLEAN
  column( Allergies ): VARCHAR
  column( HasUsualMedication ): BOOLEAN
  column( UsualMedication ): VARCHAR
}

table( ProfilePicture ) {
    primary_foreign_key( ProfileId ): INTEGER <<FK>>
    column( FileBin ): BINARY DATA
}

User -- OnBoardingUser
User --{ Profile
Profile -- ProfilePicture
@enduml