@startuml
!define LIGHTBLUE
!includeurl https://gist.githubusercontent.com/amgs/de57560012a8a5f0e4240f392b678a40/raw/c43f948dd1f23ed1b87c6c9fc972e71493859b16/style.puml
'https://plantuml.com/component-diagram
!include <tupadr3/common>
!include <office/Devices/device_tablet_android>

cloud "Hetzner Cloud" {
    node "Server" {
      frame "Localhost" {
        component "Gunicorn" {
          [Django] - ()8000
        }
      }
      [Nginx] --> ()8000:proxy
      [Nginx] - ()82:API
      database "DataBase" {
        [PostgreSQL] - ()5432
      }
    }
}

[Django] ..> 5432:uses

OFF_DEVICE_TABLET_ANDROID(app, SIREPH - Técnicos)

app .> ()82

@enduml